### PR TITLE
Preserve quotes in GetSmartContractSubState

### PR DESCRIPTION
**Pull request by KaustubhShamshery**
## Description
Earlier:
```
"params": ["9611c53BE6d1b32058b2747bdeCECed7e1216793","records",["\"0x9915d0456b878862e822e2361da37232f626a2e47505c8795134a95d36138ed3\""]]
```

Now
```   
"params": ["9611c53BE6d1b32058b2747bdeCECed7e1216793","records",["0x9915d0456b878862e822e2361da37232f626a2e47505c8795134a95d36138ed3"]]
```

for params of `GetSmartContractSubState`

## Backward Compatibility

- [x] This is not a breaking change
- [ ] This is a breaking change

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

### CODE REVIEW

**Comment by edisonljh** [comment]
Just to check - 

What if the third parameter is an array of addresses? e.g. 

```
[
"0x9915d0456b878862e822e2361da37232f626a2e47505c8795134a95d36138ed3",
"0x7505c8795134a95d36138ed39915d0456b878862e822e2361da37232f626a2e4"
]
```

What kind of error will be thrown?

**Comment by KaustubhShamshery** [comment]
> Just to check -
> 
> What if the third parameter is an array of addresses? e.g.
> 
> ```
> [
> "0x9915d0456b878862e822e2361da37232f626a2e47505c8795134a95d36138ed3",
> "0x7505c8795134a95d36138ed39915d0456b878862e822e2361da37232f626a2e4"
> ]
> ```
> 
> What kind of error will be thrown? So actually this is correct, if the a map in scilla exists such that

**Comment by edisonljh** [comment]
If the keys do not exist, will it return an empty object?

**Comment by KaustubhShamshery** [comment]
> If the keys do not exist, will it return an empty object?

`null` object

**Comment by edisonljh** [comment]
LGTM - very useful PR. Thanks!

**Pull request merged**
