### PR TITLE
Add/Modify Server APIs for feature request.

### PR DESCRIPTION
**Pull request by KaustubhShamshery**
## Description
This PR modifies CreateTransaction and adds GetContractAddressFromTransactionID APIs for ease of knowing the Contract Address.

* ### CreateTransaction
     * #### Returns a JSON containing :
     1. Error, if there is an error in creating Transaction
     2. Info, tells if the Transaction was a contract transaction and if it went to a ds shard.
     3. ContractAddress, if the transaction was a contract transaction, contains the contract Address.
* ### GetContractAddressFromTransactionID
    * Given Valid Contract Transaction ID, returns the ContractAddress (string)

## Review Suggestion
Should be merged with corresponding changes in Wallet.
Related issue : #574 

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [x] local machine test

- [ ] small-scale cloud test

### CODE REVIEW

**Comment by iantanwx** [comment]
@KaustubhShamshery sorry for the delay.

I'm not sure if these changes address #574. It seems that the feature requested is not information on the nature of the transaction (i.e., what category the TX falls into), but rather, where the transaction is actually one where a contract is to be _created_, what the resulting address of the deployed contract is.

However, having said that, I'm not sure if it's even possible to implement the feature requested at this level; we wouldn't know whether the contract was actually successfully deployed at the time of the call to `CreateTransaction`.

Am I wrong? Maybe @kaikawaliu can weigh in.

**Comment by KaustubhShamshery** [comment]
@iantanwx it provides an API given a txn, it will return the contract address.

**Comment by jiayaoqijia** [comment]
@KaustubhShamshery Can you run an AWS test?

**Comment by iantanwx** [comment]
Non-contract transactions work as expected.

**Pull request merged**
