### PR TITLE
[master] Fix waiting for pods indefinitely in localdev.py

### PR DESCRIPTION
**Pull request by yaron-zilliqa**
## Backward Compatibility

- [x] This is not a breaking change
- [ ] This is a breaking change

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

### CODE REVIEW

**Review by Steve-White-UK — CHANGES_REQUESTED** [review]
The code should not have a hard-coded constant, the actual number can be calculated from the values in the parameters to the bootstrap command.

WE have to adjust it every time you run a slightly different bootstrap, very annoying.

**Comment by yaron-zilliqa** [comment]
> 

Yes, but that value depends on the fanout value which has some strange calculation in the testnet repo.
I'd rather have that than copying all that code.

**Comment by JamesHinshelwood** [comment]
Counting the number of lines from `kubectl get pods` seems super fragile. You can probably do this with a `kubectl wait --for=condition=ready pod -l app=zilliqa` (might be the wrong label) or similar.

**Comment by yaron-zilliqa** [comment]
> 

Yes it is super fragile, except it's unfortunately needed for Prometheus' configuration and the configuration is hard coded anyway, and the script was already doing something similar. I'll see if waiting for 'ready' works.

**Review by Steve-White-UK — APPROVED** [review]

**Review by Steve-White-UK — CHANGES_REQUESTED** [review]
Needs a bit of adjustment for Q4 dev I will take a look in the morning.

**Review by Steve-White-UK — APPROVED** [review]

**Comment by rrw-zilliqa** [comment]
Closed at @yaron-zilliqa 's request.

**Pull request closed without merging**
