### PR TITLE
Support Mac OS

### PR DESCRIPTION
**Pull request by ckyang**
I've run Zilliqa on my MacOS environment, and got build error when building.
There seems to be lack of jsoncpp & json-rpc-cpp library path in some CMakeLists.txt.
Please have a review to see if it's necessary to add them.

Maybe it's not the best solution because I used absolute path inside...
link_directories(${JSONCPP_LIBDIR} /usr/local/Cellar/libjson-rpc-cpp/1.1.0/lib)

### CODE REVIEW

**Comment by bb111189** [comment]
Will need to remove the absolute path and version specific information

**Comment by ckyang** [comment]
Sure, removed in 5b409bbd453e0b248ef1dafc11305e06171733ff

**Comment by Gnnng** [comment]
The Mac build on travis was okay, so the reason of this could be different OSX versions or different brew versions. Can you refer to the travis build log [here](https://travis-ci.org/Zilliqa/Zilliqa/jobs/350833221) to check the building environment difference?

**Comment by ckyang** [comment]
After comparing travis & my environment, I found the root cause.
In my environment, following environment variable should be set:

export LIBRARY_PATH="/usr/lib:/usr/local/lib"

Then the Zilliqa compile procedure could be completed smoothly.

"/usr/local/lib" is the default library path for Mac OS, so the environment variable (LIBRARY_PATH) should always be setup as well.
Thus, I think no modification is needed.

**Pull request closed without merging**
