### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by bb111189**
## Description

This PR will improve the overall logging messages in the codebase.

## Review Suggestion

Kindly check the log-related changes.

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

### CODE REVIEW

**Comment by Gnnng** [comment]
https://github.com/Zilliqa/Zilliqa/blob/c14ec289917c9aed73101dc8f2e8d52f6207741e/src/libNetwork/P2PComm.cpp#L166-L181

@ckyang Perhaps we can refactor the log here a bit? 

In the current testnet log, `Socket read failed. Code = 11 Desc: Resource temporarily unavailable.` appears quite frequently, and the error code `11` (aka `EAGAIN`) is not a serious error. I can see from the code that we will wait and read again, however `LOG_GENERAL` is called anyway and the message is saying something wrong (`failed`) under `WARNING` level.

**Comment by Gnnng** [comment]
Multi-line logs are not friendly to line-based log analysis. Perhaps we could avoid breaking lines manually.

https://github.com/Zilliqa/Zilliqa/blob/c14ec289917c9aed73101dc8f2e8d52f6207741e/src/libDirectoryService/DSBlockPostProcessing.cpp#L443-L451

**Comment by Gnnng** [comment]
Non printable character

https://github.com/Zilliqa/Zilliqa/blob/c14ec289917c9aed73101dc8f2e8d52f6207741e/src/libNode/FinalBlockProcessing.cpp#L784-L786


```
[INFO   ][TID   153][02:47:31][LogReceivedFinalBlockDetails  ][Epoch 1] txblock.GetHeader().GetType(): ^A
```

**Comment by bb111189** [comment]
IsMessageSizeInappropriate <-- need to improve logging

**Pull request closed without merging**
