### PR TITLE
Docker image for Zilliqa

### PR DESCRIPTION
**Pull request by nickvanbaelen**
Added a Dockerfile that allows building a Docker image of Zilliqa. From this image, you can spawn Docker containers (running Ubuntu 16.04) which contain the entire Zilliqa source tree and it's built binaries.

Currently by spawning a container from this image, you can enter an interactive shell. This image can however be used to flexibly define several Docker services running a specific Zilliqa node. For example:

- one Docker service for running a Zilliqa _testnet_ node listening on _localhost_ on port _20_
- one Docker service for running a Zilliqa _mainnet_ node listening on _another IP_ on port _40_
- ...

These services would all use the same (prebuilt) Docker image to spawn their own container instance.

Let me know what you think or if you have any questions.

### CODE REVIEW

**Comment by bb111189** [comment]
This pr is related to Issue #51

**Comment by Gnnng** [comment]
Seems that the image built from this Dockerfile is a bit too large, ~1.3GB. The multiple `RUN` lines could be the cause and the solution is to merge them into few lines as much as possible.

**Comment by nickvanbaelen** [comment]
Combining multiple RUN stages into one will have a negligible effect on image size. I agree that for example the apt-get RUN's could be merged into one (or two) RUN commands to reduce some package manager overhead. Other than that, there's no reason real reason to mash several commands into one RUN command.

The majority of the current image size is represented by the ubuntu image. So if your goal is to have an image that is as small as possible, a better route to go down is to use alpine (https://store.docker.com/images/alpine). But you could potentially open yourself up to a myriad of issues since this isn't the platform the team is currently using to develop Zilliqa on.

**Comment by kishankumar258** [comment]
@nickvanbaelen  "one Docker service for running a Zilliqa testnet node listening on localhost on port 20"
Can you tell how would I proceed for doing this I am able to just run the zilliqa shell from the installed docker image

**Comment by kishankumar258** [comment]
I also want to connect multiple Docker containers locally to form a network of nodes. So that I would be able to make transactions between them. Can any one help how would I be able to do that?

**Pull request merged**
