### PR TITLE
[master] fix getBalance for Metamask compatibility

### PR DESCRIPTION
**Pull request by valeryz**
## Description
We need to return a result in eth_getBalance if/when we get a block number, even if can only serve the latest one.

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

### CODE REVIEW

**Comment by valeryz** [comment]
This PR also fixes a few errors in the previous implementation, and removes a redundant method.

Currently deployed on evmdev.  Please check your MM wallets.

**Review by moboware — CHANGES_REQUESTED** [review]
Make a unit test to check the scaling on 'overflow' number works

**Comment by valeryz** [comment]
@moboware thinking about this Unit test. It cannot really overflow, as accounts are 128 bit and are only multiplied by 1,000,000.     
Using SafeMath there is a bit of defensive programming here.

**Review by n-hutton — APPROVED** [review]

**Comment by valeryz** [comment]
> Make a unit test to check the scaling on 'overflow' number works

I don't think I can make a unit test for a scenario that never happens. Defensive programming ...

**Pull request merged**
