### PR TITLE
Fix wrong port number in tests

### PR DESCRIPTION
**Pull request by bing-chou**
## Description

Fix wrong port number in tests:
50$port --> $((5000 + $port)) since 50$port returns 501, 502... instead of 5001, 5002...

### CODE REVIEW

**Comment by Gnnng** [comment]
Hi, @bing-chou thanks for creating a pull-request for this. May I know what kind of shell you are using? In the scripts file the first line indicates that it should be run via `/bin/bash`. It works in our side so you may encounter this if you are using incompatible shells or different versions.

**Comment by bing-chou** [comment]
system:
macOS High Serria Version 10.13.6

⇒  bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.

⇒  which bash
/bin/bash

```sh
 #!/bin/bash
 for port in {01..20}
 do
     echo 50$port
 done
```

output:
501
502
503
504
505
506
507
508
509
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020

When running test_node_simple.sh, messages were found in common.log:
[TID 3218110][07:24:59][SendMessageSocketCore         ] Sending message to <127.0.0.1:507> (Len=100):                                                                                                       02030202AAB3EFF78CC0D5854AC5F3DCF2A7C372E9162340999BB8032F7B7277D698A802A523F019D0BE0E008108C012716414F6249DA59ECFF9597CC83AA4C0D825FD750000000000000000000000000000000000000000000000000000000000000064
 [TID 3218110][07:24:59][SendMessageSocketCore         ] Socket connect failed. Code = 61 Desc: Connection refused. IP address: <127.0.0.1:507>
 [TID 3218110][07:24:59][SendMessageCore               ] Socket connect failed 3/3. IP address: <127.0.0.1:507>


When using zsh, the output is ok:
⇒  zsh 0test.sh
5001
5002
5003
5004
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020

Since the bash is packeted with OS X, whose version is old, the output like “501…”  could be reproduced  when using old versions of bash, which I am not sure.

Best wishes.

**Comment by Gnnng** [comment]
Thanks a lot. We did some experiments here and confirmed the issue. We are glad to accept this PR but there's one more place to be fixed in `test_node_server.sh`. Can you kindly help to fix it as well? Or you can [allow us to edit this PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests) so that we can append the fix.

```
❯ egrep '{[0-9]+\.\.[0-9]+}' $(find . -name "*.sh" )
./tests/Node/test_node_simple.sh:for ds in {1..10}
./tests/Node/test_node_simple.sh:for node in {11..20}
./tests/Node/test_node_simple.sh:for port in {01..20}
./tests/Node/watch_node_simple.sh:for id in {01..20}
./tests/Node/test_node_server.sh:for ds in {1..20}
./tests/Node/test_node_server.sh:for node in {21..80}
./tests/Node/test_node_server.sh:for port in {21..80}
```

**Comment by Gnnng** [comment]
Hi @bing-chou just a gentle reminder: the commits you submitted are not linked to your GitHub account. Are you okay with that? You could check the solution [here](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) if you want to re-submit it.

**Comment by kaikawaliu** [comment]
Just now run 20 nodes local test got this error
`./tests/Node/test_node_simple.sh: line 50: 5000 + 08: value too great for base (error token is "08")`

**Comment by bb111189** [comment]
The shell tries to interpret 08 as an octal number, as it starts with a zero. Only digits 0-7 are, however, allowed in octal, as decimal 8 is octal 010. Hence 08 is not a valid number, and that's the reason for the error.
https://stackoverflow.com/questions/24777597/shell-script-error-value-too-great-for-base-error-token-is-08

**Comment by bing-chou** [comment]
Removing leading zero may solve the problem.  https://github.com/Zilliqa/Zilliqa/pull/539  
 
  for port in {01..20}   —>  for port in {1..20}


However, {01..20} is ok on my computer.

⇒  bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.

⇒  zsh --version
zsh 5.5.1 (x86_64-apple-darwin17.5.0)

**Pull request merged**
